create table if not exists public.users (
    user_id integer generated by default as identity primary key,
    username varchar(255) not null,
    password varchar(255) not null,
    is_active boolean not null default true,
    role varchar(40) not null default 'USER',
    constraint uk_users_username unique (username),
    constraint ck_users_role check (role in ('USER', 'ADMIN'))
);

create table if not exists public.courts (
    court_number integer primary key,
    name varchar(80) not null,
    is_active boolean not null default true,
    constraint ck_courts_number check (court_number in (1, 2))
);

insert into public.courts (court_number, name)
values
    (1, 'Volleyball Court 1'),
    (2, 'Volleyball Court 2')
on conflict (court_number) do nothing;

create table if not exists public.payments (
    payment_id integer generated by default as identity primary key,
    confirmation_token varchar(255) not null,
    payment_method varchar(40) not null,
    status varchar(40) not null default 'PENDING',
    amount_lei integer not null,
    created_at timestamp not null default now(),
    confirmed_at timestamp,
    user_id integer not null,
    constraint uk_payments_confirmation_token unique (confirmation_token),
    constraint fk_payments_user foreign key (user_id) references public.users (user_id) on delete cascade,
    constraint ck_payments_method check (payment_method in ('CARD', 'CASH_AT_REGISTRY')),
    constraint ck_payments_status check (status in ('PENDING', 'CONFIRMED'))
);

create table if not exists public.reservations (
    reservation_id integer generated by default as identity primary key,
    reservation_date date not null,
    reservation_time varchar(255) not null,
    field_number integer not null,
    status varchar(40) not null default 'RESERVED',
    user_id integer not null,
    payment_id integer,
    constraint fk_reservations_user foreign key (user_id) references public.users (user_id) on delete cascade,
    constraint fk_reservations_court foreign key (field_number) references public.courts (court_number),
    constraint fk_reservations_payment foreign key (payment_id) references public.payments (payment_id),
    constraint uk_reservation_slot unique (reservation_date, reservation_time, field_number),
    constraint ck_reservations_field_number check (field_number in (1, 2)),
    constraint ck_reservations_status check (status in ('RESERVED', 'ATTENDED', 'NO_SHOW', 'CANCELLED'))
);

alter table public.reservations add column if not exists payment_id integer;
alter table public.reservations add column if not exists status varchar(40) not null default 'RESERVED';

create index if not exists idx_reservations_field_date
    on public.reservations (field_number, reservation_date);

create index if not exists idx_reservations_user_date
    on public.reservations (user_id, reservation_date);

create index if not exists idx_reservations_status_date
    on public.reservations (status, reservation_date);

create table if not exists public.user_blacklist_entries (
    blacklist_id integer generated by default as identity primary key,
    user_id integer not null,
    reservation_id integer,
    created_by_admin_id integer,
    starts_at timestamp not null,
    ends_at timestamp not null,
    reason varchar(500),
    created_at timestamp not null default now(),
    revoked_at timestamp,
    constraint fk_blacklist_user foreign key (user_id) references public.users (user_id) on delete cascade,
    constraint fk_blacklist_reservation foreign key (reservation_id) references public.reservations (reservation_id) on delete set null,
    constraint fk_blacklist_admin foreign key (created_by_admin_id) references public.users (user_id) on delete set null,
    constraint ck_blacklist_range check (ends_at > starts_at)
);

create index if not exists idx_user_blacklist_active_user
    on public.user_blacklist_entries (user_id, revoked_at, starts_at, ends_at);

create table if not exists public.web_push_subscriptions (
    subscription_id integer generated by default as identity primary key,
    endpoint text not null,
    p256dh text not null,
    auth text not null,
    user_agent varchar(500),
    active boolean not null default true,
    created_at timestamp not null default now(),
    last_seen_at timestamp not null default now(),
    disabled_at timestamp,
    user_id integer not null,
    constraint uk_web_push_endpoint unique (endpoint),
    constraint fk_web_push_user foreign key (user_id) references public.users (user_id) on delete cascade
);

create index if not exists idx_web_push_active_user
    on public.web_push_subscriptions (active, user_id);

create index if not exists idx_users_role
    on public.users (role);
