spring.application.name=Volley_Reservations
server.port=${PORT:8080}
supabase.url=${SUPABASE_URL:https://gqxwanflddgeggfndrzh.supabase.co}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY:sb_publishable_zkjleEMVcxTcHWc-vG09qA_F1sjsSjx}
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres.gqxwanflddgeggfndrzh}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/supabase-schema.sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
